xSMD crafting recipes
GTNewHorizons/NewHorizonsCoreMod pull request #273
Opened 2022-01-31 03:51 UTC by GTNH-Colen

These are intended for wetware lines and above.

2022-01-31 03:52 UTC, GTNH-Colen commented
Open to feedback on these but I am personally happy with this as the final iteration after some thoughts and discussion with others.

2022-01-31 05:20 UTC, yukieiji commented
Personally, I think it is a good idea to double the number of outputs of the craft and reduce the consumption by a quarter for the following reasons.
1. Tiers that change from SMD to ASMD consume less ASMD
2. xSMD creation difficulty and assembly line must be used.

2022-01-31 05:28 UTC, GTNH-Colen commented
> Personally, I think it is a good idea to double the number of outputs of the craft and reduce the consumption by a quarter for the following reasons.
> 
> 1. Tiers that change from SMD to ASMD consume less ASMD
> 2. xSMD creation difficulty and assembly line must be used.

The xSMDs will only be used in wetware plus (effectively late UV/UHV+) and will fully replace the current ASMD requirements there. The assline is used but only very sparingly, 1 LuV pump can make 960 xSMD diodes and only 1 of the SMDs utilise this fact. The others have IV SCs. It's 1 pump per 15 LuV SC and 1 LuV SC per. This seems fair for the tier it is at imo.

2022-01-31 05:45 UTC, yukieiji commented
What tier of circuit crafting does xSMD support?(I'm thinking that with this consumption, I'll need another higher level SMD material before MaxV)
Current SMD consumption is as follows. I don't have to tell you that the recipes need to be balanced, but they also need to be adjusted according to the current SMD consumption.
SMD:Integrated(4 SMD) ～Quantam(64 SMD)
ASMD:Integrated(1 ASMD) ～Bio(64 ASMD)

2022-01-31 05:54 UTC, GTNH-Colen commented
It supports wetware, bio and the misc circuits above that. Nothing else. Higher tier SMDs will be introduce as more circuits are added, so worrying about their use down the line is moot for now. I'm not sure I follow the rest of your post.

Bios from my napkin maths use 96 diodes for example, this would mean 1/10th of 1 LuV pump per UEV circuit. That seems fair to me.

2022-01-31 06:05 UTC, GlodBlock commented
do you just choose some random expensive material for xsmd? honestly, i can't get the point of why choose them

2022-01-31 06:08 UTC, GTNH-Colen commented
> do you just choose some random expensive material for xsmd? honestly, i can't get the point of why choose them

No this was deliberately chosen to integrate GT++ materials better into the pack (these materials are all ZPM tier in the ABS). I didn't realise there was a correct xSMD recipe that uses materials you approved of, can you share it with me if so?

2022-01-31 06:48 UTC, GlodBlock commented
the problem isn't tier or gt++ but the material itself.
these gt++ alloy are classic heat/pressure/corrosion material for their origin use in gt++, how they will be suitable for these mirco ciruit part?
resistor should choose materials with high resistance and voltage like duranium/naquadah alloy.
transistor and diode material should be semiconductor, but there is not enough suitable choice in game currently, quantum alloy containing germanium and gallium so seems fine but it is uhv.
capacitor material should be able to hold great potential difference like zirconia.
what you choosed should be the machine part material instead of the ciruit.

2022-01-31 06:57 UTC, GTNH-Colen commented
Dude it's a game with made up space metals, I'm really not going into super realism of the exact conductivity of each material and how it would hypothetically interact in a made up circuit.

Like I get simple realism such as using copper as a conductor etc but this is extreme endgame with made up alloys/metals, no one is playing GTNH and thinking "damn why is Pikyonium 64B used in a SMD, the chemical composition makes no sense!".

2022-01-31 07:06 UTC, boubou19 commented
why do i have the feeling that people try to find reasons to reject GT++ alloys because they come from GT++ 🤔

2022-01-31 07:16 UTC, GlodBlock commented
i am not mean to follow the reality strictly but at least not completely go beyond it. like why don't volcanus use cryotheum as fuel because it counters common sense. ofc both cryotheum and pytrotheum are made up material from TE.
also most gt++ alloy exist in real life, few from other game like world of warcraft, only very very few is completely made up and even these made up one are following certain rules like the quantum alloy i mentioned above.

2022-01-31 07:26 UTC, GTNH-Colen commented
These alloys are literally named after people in the community, they are made up names.

- Pikyonium = Piky
- Lafium = 0lafe
- Cinobite = Cinobi
- Arceus2B = Pokemon I guess? Lol

2022-01-31 19:10 UTC, Dream-Master requested changes

2022-01-31 19:10 UTC, Dream-Master commented on src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java
> +                new FluidStack[]{Oil.getFluid(1)},
this is change we need to discuss. You cahnage from 1000 to 1.
And this change not belongs to the xsmd's so please seperate it

2022-01-31 19:10 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +        // xSMD
I would like so see one more component in the recipe so we add each tier a component

2022-01-31 19:10 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +            GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Chip_NeuroCPU.get(1L), ItemList.Circuit_Chip_CrystalCPU.get(1L), ItemList.Circuit_Chip_NanoCPU.get(1L), ItemList.Ci
Please not exchange asmd with xsmd. Xsmd are better asmds so they need to be add to make new recipes with lower amount of xsmd's

2022-02-01 23:04 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +        // xSMD
yea looks good now. Will check ingame

2022-02-01 23:05 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +            GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Chip_NeuroCPU.get(1L), ItemList.Circuit_Chip_CrystalCPU.get(1L), ItemList.Circuit_Chip_NanoCPU.get(1L), ItemList.Ci
i would suggest tier up this one tier like smd recipes are cheaper than asmd recipe (tier wise)

2022-02-01 23:05 UTC, Dream-Master requested changes

2022-02-01 23:05 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +            GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Board_Wetware_Extreme.get(1L), ItemList.Circuit_Neuroprocessor.get(2L), ItemList.Circuit_Parts_Coil.get(32L), ItemL
i would suggest tier up this one tier like smd recipes are cheaper than asmd recipe (tier wise)

2022-02-01 23:05 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +            GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Chip_BioCPU.get(1L), ItemList.Circuit_Chip_CrystalSoC2.get(1L), ItemList.Circuit_Chip_NanoCPU.get(2L), ItemList.Cir
i would suggest tier up this one tier like smd recipes are cheaper than asmd recipe (tier wise)

2022-02-01 23:05 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +            GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Board_Bio_Ultra.get(1L), ItemList.Circuit_Bioprocessor.get(2L), ItemList.Circuit_Parts_Coil.get(48L), ItemList.Circ
i would suggest tier up this one tier like smd recipes are cheaper than asmd recipe (tier wise)

2022-02-01 23:07 UTC, Dream-Master commented on src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java
> +                new FluidStack[]{Oil.getFluid(1)},
ok yea use 1000 is very much. I would use 10 as values but yea

2022-02-09 04:18 UTC, GTNH-Colen commented
This is effectively done now, only issue that needs resolving is the research conflict. My initial proposal of a new item with the xSMD in the corner which can be assembled with a circuit and xSMD stands. This makes logical sense as it is as if you are researching the circuit with the xSMD. If no one objects to this soon I will implement it because this change has dragged its feet for far too long due to way too much interference. Example image below. Also leaves open the door for even higher SMDs with similar research.
<img width="248" alt="Screenshot 2022-02-09 at 04 15 31" src="https://user-images.githubusercontent.com/54497873/153120796-927237e1-3d45-4450-be11-5d0d1346f71b.png">

2022-02-09 08:56 UTC, Dream-Master commented
> This is effectively done now, only issue that needs resolving is the research conflict. My initial proposal of a new item with the xSMD in the corner which can be assembled with a circuit and xSMD stands. This makes logical sense as it is as if you are researching the circuit with the xSMD. If no one objects to this soon I will implement it because this change has dragged its feet for far too long due to way too much interference. Example image below. Also leaves open the door for even higher SMDs with similar research. <img alt="Screenshot 2022-02-09 at 04 15 31" width="248" src="https://user-images.githubusercontent.com/54497873/153120796-927237e1-3d45-4450-be11-5d0d1346f71b.png">

Lets make a concept first and not adding items we later not use in any recipes.

2022-02-09 13:37 UTC, Dream-Master approved these changes

2022-02-09 13:37 UTC, merged