Removing some small/tiny dusts from recipes
GTNewHorizons/NewHorizonsCoreMod pull request #292
Opened 2022-02-26 19:27 UTC by LewisSaber

im too stupid to use github properly reee

2022-02-26 19:28 UTC, LewisSaber commented
Gotta remove small dusts from planet stone crushing, should i multiply amount of stone needed OR lower dust chance

2022-02-26 19:28 UTC, LewisSaber commented
@Dream-Master

2022-02-26 20:55 UTC, Dream-Master commented
will check

2022-02-26 21:06 UTC, Dream-Master requested changes

2022-02-26 21:06 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +        GT_Values.RA.addCentrifugeRecipe(GT_OreDictUnificator.get(OrePrefixes.dust.get(Materials.DeepIron), 4L), GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dust, M
looks ok

2022-02-26 21:06 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +        GT_Values.RA.addCentrifugeRecipe(GT_OreDictUnificator.get(OrePrefixes.dust, Materials.QuartzSand, 9L), GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dust, Mat
i would lower the processing time. Sure it was more expensive before but i lower it for stone dust production as well

2022-02-26 21:11 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +        GT_Values.RA.addCentrifugeRecipe(GT_OreDictUnificator.get(OrePrefixes.dust, Materials.QuartzSand, 9L), GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dust, Mat
maybe use 2400

2022-02-26 21:12 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +        GT_Values.RA.addCentrifugeRecipe(GT_OreDictUnificator.get(OrePrefixes.dust, Materials.QuartzSand, 9L), GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dust, Mat
compared to stone dust use 108 sec = 2160

2022-02-27 11:02 UTC, Dream-Master commented on src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
> +        GT_Values.RA.addCentrifugeRecipe(GT_OreDictUnificator.get(OrePrefixes.dust.get(Materials.DeepIron), 4L), GT_Values.NI, GT_Values.NF, GT_Values.NF, GT_OreDictUnificator.get(OrePrefixes.dust, M
you forgot two GT_Values.NI,  the centrifuge need 6 output slot items definied or GT_Values.NI,

2022-02-27 11:37 UTC, merged