Add new bio circuit recipe aka bio SoC + adjust wetware SoC
GTNewHorizons/NewHorizonsCoreMod pull request #554
Opened 2023-04-04 20:45 UTC by GDCloudstrike

Adds a simpler, higher tier recipe for bio circuits which does not require bio processing units. This alternate recipe uses a new bio chip which is made from a new wafer. 

The wafer requires an optical wafer, bio medium and hypogen dust, making it unviable pre-dtpf, but relatively cheap after you have one, which was the goal.
![image](https://user-images.githubusercontent.com/93287602/229915801-7e5897b6-73a7-42c2-8ead-2b6f22da2c37.png)

The wafer then has to be cut with uum to obtain the bio chips and some biocells
![image](https://user-images.githubusercontent.com/93287602/229916009-b57656e8-0215-4a0f-82f3-1b1aa88b9eeb.png)

Finally the chips can be turned into bioprocessors with circuit boards, some wire and chromatic glass bolts, which also reinforce the trend of obtainable pre-dtpf, but not worth it pre-dtpf
![image](https://user-images.githubusercontent.com/93287602/229916104-9109d0e3-6cd7-4250-9a0c-83aaeba4602a.png)

Also adjusted the wetware SoC time from 3 to 2.5 seconds to make it consistent with the other SoC recipes

2023-04-05 08:29 UTC, boubou19 requested changes

2023-04-05 08:29 UTC, boubou19 commented on src/main/java/com/dreammaster/gthandler/recipes/AutoclaveRecipes.java
> +                    60 * 20,
please write `60*SECONDS`

2023-04-05 08:29 UTC, boubou19 commented on src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
> +                50,
Please write `2*SECONDS+10*TICKS`

2023-04-05 08:29 UTC, boubou19 commented on src/main/java/com/dreammaster/gthandler/recipes/CuttingMachineRecipes.java
> +                15 * 20,
Please write `15*SECONDS`

2023-04-05 08:29 UTC, boubou19 commented on src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
> +                    2457600,
Please use the appropriate recipe voltage in `TierEU`

2023-04-05 08:29 UTC, boubou19 commented on src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
> +                    75,
Please write `3*SECONDS+15*TICKS`

2023-04-05 14:29 UTC, Dream-Master commented
@GDCloudstrike i am not familiar with new Ra 2 code but let only add new recipes via the new format.

2023-04-06 07:34 UTC, Dream-Master approved these changes

2023-04-06 07:34 UTC, merged